<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">

    <title>Allmyhomes OpenShift Example</title>
</head>
<body>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-xl-8 col-lg-10 col-12">
            <h1 class="text-center">
                Test Blog
            </h1>
        </div>
    </div>

    <?php if (isset($articles) && !empty($articles)):
        foreach ($articles as $article): ?>
            <div class="row justify-content-center">
                <div class="col-xl-8 col-lg-10 col-12">
                    <div class="card text-center">
                        <div class="card-header">
                            <?= htmlspecialchars($article["title"]) ?>
                        </div>
                        <div class="card-body">
                            <p class="card-text">
                                <?= nl2br(htmlspecialchars($article["text"])) ?>
                            </p>
                        </div>
                        <div class="card-footer text-muted">
                            <?php
                            $date = strtotime($article["created"]);
                            echo "Created at " . date("Y-m-d", $date);
                            ?>
                        </div>
                    </div>
                </div>
            </div>
    <?php
        endforeach;
    else: ?>
        <div class="row justify-content-center">
            <div class="col-xl-8 col-lg-10 col-12">
                <div class="alert alert-warning">
                    There are no articles yet ...  Stay tuned for interesting content.
                </div>
            </div>
        </div>
    <?php endif; ?>


</div>


<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
</body>
</html>